import type { AffairsState, LedgerRecord } from './types'

function row(id: string, data: Record<string, string | number>): LedgerRecord {
  return { ...data, id }
}

const tasks: LedgerRecord[] = [
  row('task-risk-xinglan', {
    title: '复核星澜智造危化品暂存台账',
    parkId: 'park-binjiang',
    kind: '预警',
    priority: '紧急',
    status: '未办',
    owner: '陈启明',
    dueAt: '2026-10-04',
    source: '风险画像',
    summary: 'A1 研发楼暂存间缺一页领用记录，需值班席今天内核对企业安全员。',
  }),
  row('task-land-yq-east', {
    title: '云栖东侧预留地块供应会商',
    parkId: 'park-binjiang',
    kind: '会商',
    priority: '普通',
    status: '办理中',
    owner: '刘澄',
    dueAt: '2026-10-08',
    source: '用地监管',
    summary: '规划用途为科研，现状未利用。会商是否纳入下一季供应计划。',
  }),
  row('task-complaint-odor', {
    title: '临港南侧异味投诉回访',
    parkId: 'park-lingang',
    kind: '待办',
    priority: '紧急',
    status: '办理中',
    owner: '周岚',
    dueAt: '2026-10-03',
    source: '投诉举报',
    summary: '夜间装卸投诉已分派物业，需在办结前电话回访投诉人。',
  }),
  row('task-submit-sept', {
    title: '报送九月在园企业增减表',
    parkId: 'park-guanggu',
    kind: '待办',
    priority: '普通',
    status: '未办',
    owner: '周岚',
    dueAt: '2026-10-06',
    source: '数据报送',
    summary: '光谷生命待入驻企业两家，增减表需单独注明手续未齐。',
  }),
  row('task-assess-safety', {
    title: '临港安全指标补件',
    parkId: 'park-lingang',
    kind: '待办',
    priority: '普通',
    status: '办理中',
    owner: '陈启明',
    dueAt: '2026-10-09',
    source: '园区考核',
    summary: '特种设备检验临期材料未齐，考核填报先挂办理中。',
  }),
  row('task-policy-talent', {
    title: '人才租房补贴条文核对',
    parkId: 'park-binjiang',
    kind: '会商',
    priority: '知悉',
    status: '已办结',
    owner: '周岚',
    dueAt: '2026-09-28',
    source: '政策管理',
    summary: '草案适用对象已改为在园企业，条文核对完毕。',
  }),
  row('task-idle-m2', {
    title: '光谷 C2 中试楼闲置盘活提醒',
    parkId: 'park-guanggu',
    kind: '预警',
    priority: '普通',
    status: '未办',
    owner: '刘澄',
    dueAt: '2026-10-07',
    source: '闲置台账',
    summary: '中试楼空置跨月，需对照闲置清单确认是否进入洽谈。',
  }),
  row('task-briefing', {
    title: '管委会周一监管例会材料',
    parkId: 'park-binjiang',
    kind: '待办',
    priority: '知悉',
    status: '已办结',
    owner: '陈启明',
    dueAt: '2026-09-29',
    source: '工作台',
    summary: '例会只摘高风险两家和超时投诉一件，材料已归档。',
  }),
]

const risks: LedgerRecord[] = [
  row('risk-xinglan', {
    enterpriseId: 'ent-xinglan',
    parkId: 'park-binjiang',
    level: '高风险',
    dimension: '安全',
    signal: '危化品暂存台账缺页',
    score: 82,
    status: '待核查',
    owner: '陈启明',
    updatedAt: '2026-09-28',
    note: '领用记录 9 月 26 日断档。先核对企业安全员，再决定是否约谈。',
  }),
  row('risk-qinghe', {
    enterpriseId: 'ent-qinghe',
    parkId: 'park-binjiang',
    level: '中风险',
    dimension: '环保',
    signal: '废水在线监测夜间波动',
    score: 64,
    status: '处置中',
    owner: '周岚',
    updatedAt: '2026-09-26',
    note: '企业称清洗批次增加。已要求补传七日曲线和转运联单。',
  }),
  row('risk-luanshu', {
    enterpriseId: 'ent-luanshu',
    parkId: 'park-binjiang',
    level: '关注',
    dimension: '信用',
    signal: '待入驻，社保开户未完成',
    score: 41,
    status: '待核查',
    owner: '周岚',
    updatedAt: '2026-09-20',
    note: '入驻手续未齐，画像先挂关注，不升为经营异常。',
  }),
  row('risk-haiyi', {
    enterpriseId: 'ent-haiyi',
    parkId: 'park-lingang',
    level: '中风险',
    dimension: '安全',
    signal: '特种设备检验临期',
    score: 70,
    status: '处置中',
    owner: '刘澄',
    updatedAt: '2026-09-18',
    note: '两台起重机械检验将于十月中旬到期，已列入临港安全补件。',
  }),
  row('risk-yuanneng', {
    enterpriseId: 'ent-yuanneng',
    parkId: 'park-lingang',
    level: '高风险',
    dimension: '安全',
    signal: '储能舱消防演练缺席',
    score: 86,
    status: '待核查',
    owner: '陈启明',
    updatedAt: '2026-09-29',
    note: '季度演练签到表没有远能动力。需现场核对是否另册记录。',
  }),
  row('risk-jinfan', {
    enterpriseId: 'ent-jinfan',
    parkId: 'park-lingang',
    level: '低风险',
    dimension: '经营',
    signal: '已迁出，保证金未清',
    score: 28,
    status: '已闭环',
    owner: '周岚',
    updatedAt: '2026-08-30',
    note: '保证金已于八月结清，档案保留，不再跟踪。',
  }),
  row('risk-baiyu', {
    enterpriseId: 'ent-baiyu',
    parkId: 'park-guanggu',
    level: '中风险',
    dimension: '环保',
    signal: '中试废液转运联单滞后',
    score: 61,
    status: '处置中',
    owner: '刘澄',
    updatedAt: '2026-09-15',
    note: '待入驻期间已开展中试。联单滞后三天，要求补齐后再复评。',
  }),
  row('risk-qiming', {
    enterpriseId: 'ent-qiming',
    parkId: 'park-guanggu',
    level: '低风险',
    dimension: '信用',
    signal: '纳税信用波动提示',
    score: 33,
    status: '已闭环',
    owner: '周岚',
    updatedAt: '2026-09-02',
    note: '税务部门提示已撤回，企业说明为申报更正，闭环留档。',
  }),
]

const lands: LedgerRecord[] = [
  row('land-yq-w', {
    name: '云栖西侧工业地块',
    parkId: 'park-binjiang',
    code: 'YQ-W-03',
    planUse: '工业',
    actualUse: '工业',
    areaMu: 86,
    supplyStatus: '已供应',
    holder: '星澜智造科技有限公司',
    suppliedAt: '2021-03-01',
    note: '与 A1 研发楼毗邻，实际利用与规划用途一致。',
  }),
  row('land-yq-n', {
    name: '云栖北侧科研地块',
    parkId: 'park-binjiang',
    code: 'YQ-N-07',
    planUse: '科研',
    actualUse: '科研',
    areaMu: 42,
    supplyStatus: '已供应',
    holder: '滨江云栖科创园管委会',
    suppliedAt: '2018-06-12',
    note: '公共实验配套，不单独出租给单一企业。',
  }),
  row('land-yq-e', {
    name: '云栖东侧预留地块',
    parkId: 'park-binjiang',
    code: 'YQ-E-11',
    planUse: '科研',
    actualUse: '未利用',
    areaMu: 28,
    supplyStatus: '待供应',
    holder: '滨江云栖科创园管委会',
    suppliedAt: '2026-12-01',
    note: '计划供应日期为预计值。现状围挡空地，未开工。',
  }),
  row('land-lg-m', {
    name: '临港 M 区制造地块',
    parkId: 'park-lingang',
    code: 'LG-M-01',
    planUse: '工业',
    actualUse: '工业',
    areaMu: 160,
    supplyStatus: '已供应',
    holder: '海弈装备股份有限公司',
    suppliedAt: '2020-04-20',
    note: '智能厂房所在地块，利用强度高。',
  }),
  row('land-lg-s', {
    name: '临港南侧物流地块',
    parkId: 'park-lingang',
    code: 'LG-S-04',
    planUse: '商服',
    actualUse: '临时',
    areaMu: 54,
    supplyStatus: '已收回',
    holder: '锦帆物流科技有限公司',
    suppliedAt: '2019-09-01',
    note: '企业已迁出。地块临时堆场，待重新明确用途。',
  }),
  row('land-gg-w', {
    name: '光谷生命西区中试地块',
    parkId: 'park-guanggu',
    code: 'GG-W-02',
    planUse: '科研',
    actualUse: '科研',
    areaMu: 73,
    supplyStatus: '已供应',
    holder: '启明医疗器械有限公司',
    suppliedAt: '2022-01-08',
    note: '与 C1 研发中心配套，中试与研发混用。',
  }),
  row('land-gg-e', {
    name: '光谷生命东区预留地块',
    parkId: 'park-guanggu',
    code: 'GG-E-06',
    planUse: '工业',
    actualUse: '未利用',
    areaMu: 39,
    supplyStatus: '待供应',
    holder: '光谷生命科学园建设指挥部',
    suppliedAt: '2027-03-01',
    note: '园区仍在建设期，东区暂不供应。',
  }),
]

const assessments: LedgerRecord[] = [
  row('assess-bj-run', {
    name: '载体出租率',
    parkId: 'park-binjiang',
    category: '运行',
    cycle: '2026 年三季度',
    progress: '已评分',
    score: 88,
    owner: '刘澄',
    deadline: '2026-10-15',
    note: '用房台账在用比例高于考核线，待归档。',
  }),
  row('assess-bj-invest', {
    name: '新入驻企业数',
    parkId: 'park-binjiang',
    category: '招商',
    cycle: '2026 年三季度',
    progress: '填报中',
    score: 0,
    owner: '周岚',
    deadline: '2026-10-12',
    note: '峦数信息仍为待入驻，是否计入需经济发展局确认。',
  }),
  row('assess-lg-safe', {
    name: '特种设备按期检验率',
    parkId: 'park-lingang',
    category: '安全',
    cycle: '2026 年三季度',
    progress: '填报中',
    score: 0,
    owner: '陈启明',
    deadline: '2026-10-09',
    note: '海弈装备两台设备临期，材料未齐。',
  }),
  row('assess-lg-service', {
    name: '投诉按期办结率',
    parkId: 'park-lingang',
    category: '服务',
    cycle: '2026 年三季度',
    progress: '已评分',
    score: 76,
    owner: '周岚',
    deadline: '2026-10-15',
    note: '有一件异味投诉仍在办理，得分先按过程分计。',
  }),
  row('assess-gg-run', {
    name: '在建项目手续完备率',
    parkId: 'park-guanggu',
    category: '运行',
    cycle: '2026 年上半年',
    progress: '已归档',
    score: 81,
    owner: '刘澄',
    deadline: '2026-07-20',
    note: '上半年结果已归档，建设期指标单独说明。',
  }),
  row('assess-gg-safe', {
    name: '中试危废联单及时率',
    parkId: 'park-guanggu',
    category: '安全',
    cycle: '2026 年三季度',
    progress: '未开始',
    score: 0,
    owner: '刘澄',
    deadline: '2026-10-18',
    note: '白屿合成生物联单滞后，填报尚未启动。',
  }),
  row('assess-bj-service', {
    name: '政策兑现答复时效',
    parkId: 'park-binjiang',
    category: '服务',
    cycle: '2026 年上半年',
    progress: '已归档',
    score: 91,
    owner: '周岚',
    deadline: '2026-07-18',
    note: '上半年人才补贴咨询均在五个工作日内答复。',
  }),
  row('assess-lg-invest', {
    name: '制造业投资到位额',
    parkId: 'park-lingang',
    category: '招商',
    cycle: '2025 年度',
    progress: '已归档',
    score: 84,
    owner: '周岚',
    deadline: '2026-01-31',
    note: '年度结果仅作对照，不在本季改分。',
  }),
]

const policies: LedgerRecord[] = [
  row('policy-rent', {
    title: '在园企业研发用房租金补助办法',
    docNo: '滨园管〔2026〕12 号',
    parkId: 'park-binjiang',
    category: '扶持',
    audience: '在园企业',
    coverage: '本园',
    status: '已发布',
    issuedAt: '2026-03-18',
    summary: '对在园且信用无异常的研发企业，按实际承租面积分档补助。已迁出企业不追溯。',
  }),
  row('policy-safety', {
    title: '园区危化品暂存管理办法',
    docNo: '三园联〔2026〕4 号',
    parkId: 'park-binjiang',
    category: '安全',
    audience: '在园企业',
    coverage: '三园',
    status: '已发布',
    issuedAt: '2026-05-06',
    summary: '暂存间须日清日结。台账缺页视为安全信号，进入风险画像待核查。',
  }),
  row('policy-talent', {
    title: '科创人才租房补贴实施细则',
    docNo: '滨园管〔2026〕19 号',
    parkId: 'park-binjiang',
    category: '人才',
    audience: '在园企业',
    coverage: '本园',
    status: '草案',
    issuedAt: '2026-09-20',
    summary: '草案把适用对象从拟入驻改为在园满六个月。尚未上会。',
  }),
  row('policy-env', {
    title: '临港制造园区夜间装卸管理指引',
    docNo: '临园管〔2025〕27 号',
    parkId: 'park-lingang',
    category: '监管',
    audience: '在园企业',
    coverage: '本园',
    status: '已发布',
    issuedAt: '2025-11-02',
    summary: '二十二时后限制高噪声装卸。投诉热线与物业值班电话写在附件。',
  }),
  row('policy-waste', {
    title: '中试废液转运联单规范',
    docNo: '光园建〔2026〕8 号',
    parkId: 'park-guanggu',
    category: '监管',
    audience: '在园企业',
    coverage: '本园',
    status: '已发布',
    issuedAt: '2026-02-14',
    summary: '中试活动即使尚未正式入驻，也要按日填报转运联单。',
  }),
  row('policy-old', {
    title: '入园备案一次性奖励',
    docNo: '临园管〔2019〕3 号',
    parkId: 'park-lingang',
    category: '扶持',
    audience: '拟入驻企业',
    coverage: '本园',
    status: '已废止',
    issuedAt: '2019-04-01',
    summary: '奖励已并入市级条款，本园条文废止，档案保留备查。',
  }),
  row('policy-org', {
    title: '园区值班信息报送规定',
    docNo: '三园联〔2024〕11 号',
    parkId: 'park-guanggu',
    category: '监管',
    audience: '园区机构',
    coverage: '三园',
    status: '已发布',
    issuedAt: '2024-12-09',
    summary: '高风险信号和超时投诉须在下一工作日例会上说明。',
  }),
]

const complaints: LedgerRecord[] = [
  row('case-odor', {
    title: '临港南侧夜间装卸异味',
    parkId: 'park-lingang',
    channel: '来电',
    category: '环境',
    status: '办理中',
    assignee: '周岚',
    complainant: '韩柏',
    phone: '021-58002901',
    receivedAt: '2026-09-27',
    deadline: '2026-10-04',
    content: '投诉人称二十二时后仍有溶剂气味。已分派物业夜巡，待回访。',
  }),
  row('case-lift', {
    title: '云栖 A1 货梯高峰停运',
    parkId: 'park-binjiang',
    channel: '网络',
    category: '物业',
    status: '已办结',
    assignee: '刘澄',
    complainant: '赵衡',
    phone: '0571-86001902',
    receivedAt: '2026-09-12',
    deadline: '2026-09-19',
    content: '货梯保养与上班高峰重叠。物业已改到清晨，企业确认办结。',
  }),
  row('case-noise', {
    title: '光谷 C2 中试楼施工噪声',
    parkId: 'park-guanggu',
    channel: '现场',
    category: '环境',
    status: '待受理',
    assignee: '刘澄',
    complainant: '许屿',
    phone: '027-87003903',
    receivedAt: '2026-10-01',
    deadline: '2026-10-08',
    content: '东区预留地块围挡施工，中试楼白天噪声偏大。尚未分派施工单位。',
  }),
  row('case-wage', {
    title: '临港保洁班组工资拖延',
    parkId: 'park-lingang',
    channel: '来信',
    category: '劳务',
    status: '办理中',
    assignee: '陈启明',
    complainant: '罗夏',
    phone: '021-58002904',
    receivedAt: '2026-09-18',
    deadline: '2026-10-02',
    content: '物业分包单位九月工资未发。已要求园区物业限时说明。',
  }),
  row('case-fire', {
    title: '云栖 B2 消防通道堆物',
    parkId: 'park-binjiang',
    channel: '现场',
    category: '安全',
    status: '已办结',
    assignee: '陈启明',
    complainant: '林知夏',
    phone: '0571-86001905',
    receivedAt: '2026-08-21',
    deadline: '2026-08-28',
    content: '实验耗材暂放通道。企业当日清运，复查通过。',
  }),
  row('case-park', {
    title: '光谷访客车位被占用',
    parkId: 'park-guanggu',
    channel: '网络',
    category: '物业',
    status: '已退回',
    assignee: '周岚',
    complainant: '曹湖',
    phone: '027-87003906',
    receivedAt: '2026-09-05',
    deadline: '2026-09-12',
    content: '事项属园区物业合同，不在监管投诉范围，已退回并告知服务热线。',
  }),
  row('case-dust', {
    title: '临港 M 区打磨粉尘外溢',
    parkId: 'park-lingang',
    channel: '来电',
    category: '环境',
    status: '待受理',
    assignee: '周岚',
    complainant: '蒋潮',
    phone: '021-58002907',
    receivedAt: '2026-10-02',
    deadline: '2026-10-09',
    content: '相邻工位反映打磨间负压不足。受理后需对照安全巡查。',
  }),
  row('case-other', {
    title: '云栖食堂供餐时间咨询',
    parkId: 'park-binjiang',
    channel: '来信',
    category: '其他',
    status: '已办结',
    assignee: '周岚',
    complainant: '方麓',
    phone: '0571-86001908',
    receivedAt: '2026-07-03',
    deadline: '2026-07-10',
    content: '咨询件，已答复供餐时间，不作为投诉考核。',
  }),
]

const submissions: LedgerRecord[] = [
  row('submit-bj-ent', {
    title: '在园企业增减月报',
    parkId: 'park-binjiang',
    period: '2026 年 9 月',
    target: '经济发展局',
    status: '已报送',
    owner: '周岚',
    dueAt: '2026-10-05',
    receiptNo: 'BJ-2026-09-014',
    note: '九月无迁出。待入驻一家已在备注单列。',
  }),
  row('submit-lg-land', {
    title: '用地供应与收回季报',
    parkId: 'park-lingang',
    period: '2026 年三季度',
    target: '规划建设局',
    status: '填报中',
    owner: '刘澄',
    dueAt: '2026-10-12',
    receiptNo: '',
    note: '南侧物流地块收回原因需与闲置台账核对后再报。',
  }),
  row('submit-gg-safe', {
    title: '中试安全隐患月报',
    parkId: 'park-guanggu',
    period: '2026 年 9 月',
    target: '应急管理局',
    status: '待填报',
    owner: '陈启明',
    dueAt: '2026-10-06',
    receiptNo: '',
    note: '废液联单滞后要写入隐患，不要并进一般物业问题。',
  }),
  row('submit-bj-energy', {
    title: '研发楼用电月报',
    parkId: 'park-binjiang',
    period: '2026 年 8 月',
    target: '管委会办公室',
    status: '已报送',
    owner: '刘澄',
    dueAt: '2026-09-08',
    receiptNo: 'BJ-2026-08-006',
    note: '八月回执已存档，仅供对照。',
  }),
  row('submit-lg-staff', {
    title: '用工与社保季报',
    parkId: 'park-lingang',
    period: '2026 年三季度',
    target: '经济发展局',
    status: '已退回',
    owner: '周岚',
    dueAt: '2026-10-10',
    receiptNo: 'LG-2026-Q3-003',
    note: '已迁出企业仍被计入在岗人数，退回后需重报。',
  }),
  row('submit-gg-progress', {
    title: '在建载体进度月报',
    parkId: 'park-guanggu',
    period: '2026 年 9 月',
    target: '规划建设局',
    status: '填报中',
    owner: '刘澄',
    dueAt: '2026-10-07',
    receiptNo: '',
    note: '东区预留地块保持未开工，不要写成已供应。',
  }),
  row('submit-all-duty', {
    title: '值班信息周报',
    parkId: 'park-binjiang',
    period: '2026 年 9 月',
    target: '管委会办公室',
    status: '已报送',
    owner: '陈启明',
    dueAt: '2026-09-30',
    receiptNo: 'ZB-2026-09-W4',
    note: '覆盖三园高风险和超时投诉，由云栖值班席汇总。',
  }),
]

const reports: LedgerRecord[] = [
  row('report-ent', {
    title: '在园企业结构月报',
    parkId: 'park-binjiang',
    theme: '企业',
    cycle: '月报',
    status: '可导出',
    owner: '周岚',
    updatedAt: '2026-10-01',
    summary: '三园在册企业以在园为主，临港有一家已迁出档案，云栖和光谷各有待入驻。',
    basis: '口径取企业名录当前状态，不含已删除的演示草稿。',
  }),
  row('report-space', {
    title: '用地利用对照季报',
    parkId: 'park-lingang',
    theme: '空间',
    cycle: '季报',
    status: '编制中',
    owner: '刘澄',
    updatedAt: '2026-09-25',
    summary: '规划用途与实际利用不一致的地块集中在临港南侧和两个预留地块。',
    basis: '只统计用地台账，不画空间分布。',
  }),
  row('report-risk', {
    title: '风险信号跟踪月报',
    parkId: 'park-binjiang',
    theme: '风险',
    cycle: '月报',
    status: '编制中',
    owner: '陈启明',
    updatedAt: '2026-09-29',
    summary: '高风险两家均属安全维度，尚未闭环。信用类低风险已有闭环样本。',
    basis: '等级取风险画像最新一条，不合并历史分数。',
  }),
  row('report-case', {
    title: '投诉办结时效季报',
    parkId: 'park-lingang',
    theme: '投诉',
    cycle: '季报',
    status: '可导出',
    owner: '周岚',
    updatedAt: '2026-09-30',
    summary: '环境类仍有待受理和办理中。物业咨询件已办结或退回的不进超时。',
    basis: '时限按受理日期加七个自然日，演示数据手工填写。',
  }),
  row('report-assess', {
    title: '考核进度年报',
    parkId: 'park-guanggu',
    theme: '考核',
    cycle: '年报',
    status: '已归档',
    owner: '刘澄',
    updatedAt: '2026-02-18',
    summary: '上年度安全与运行指标已归档。建设期园区单独附说明。',
    basis: '归档后不允许在本页改历史得分，新周期另建条目。',
  }),
  row('report-idle', {
    title: '闲置盘活对照月报',
    parkId: 'park-guanggu',
    theme: '空间',
    cycle: '月报',
    status: '编制中',
    owner: '刘澄',
    updatedAt: '2026-09-22',
    summary: '文字摘要指向闲置台账，本页不重复维护房号。',
    basis: '明细仍以空间监管的闲置列表为准。',
  }),
]

const settings: LedgerRecord[] = [
  row('set-org-duty', {
    name: '管委会值班室',
    category: '组织架构',
    code: 'ORG-DUTY',
    scope: '平台',
    status: '启用',
    value: '值班席',
    owner: '陈启明',
    note: '三园共用值班口径，云栖为汇总点。',
  }),
  row('set-org-eco', {
    name: '经济发展局企业科',
    category: '组织架构',
    code: 'ORG-ECO',
    scope: '滨江云栖',
    status: '启用',
    value: '企业监管',
    owner: '周岚',
    note: '负责名录、政策和投诉中的经济类事项。',
  }),
  row('set-org-plan', {
    name: '规划建设局空间科',
    category: '组织架构',
    code: 'ORG-PLAN',
    scope: '临港智造',
    status: '启用',
    value: '空间监管',
    owner: '刘澄',
    note: '用地、用房、闲置的牵头科室。光谷建设期事项一并对照。',
  }),
  row('set-role-duty', {
    name: '值班席',
    category: '角色权限',
    code: 'ROLE-DUTY',
    scope: '平台',
    status: '启用',
    value: '可查看全部台账',
    owner: '陈启明',
    note: '演示角色只做说明，不做真实权限拦截。',
  }),
  row('set-role-ent', {
    name: '企业监管专员',
    category: '角色权限',
    code: 'ROLE-ENT',
    scope: '滨江云栖',
    status: '启用',
    value: '企业、投诉、政策',
    owner: '周岚',
    note: '与登录账号周岚的岗位说明一致。',
  }),
  row('set-role-space', {
    name: '空间监管专员',
    category: '角色权限',
    code: 'ROLE-SPACE',
    scope: '光谷生命',
    status: '启用',
    value: '用地、用房、闲置',
    owner: '刘澄',
    note: '与登录账号刘澄的岗位说明一致。',
  }),
  row('set-dict-risk', {
    name: '风险等级',
    category: '字典参数',
    code: 'DICT-RISK',
    scope: '平台',
    status: '启用',
    value: '高风险,中风险,低风险,关注',
    owner: '陈启明',
    note: '画像页下拉与此保持一致，改字典不会自动改历史记录。',
  }),
  row('set-dict-old', {
    name: '已废止的入园奖励档次',
    category: '字典参数',
    code: 'DICT-BONUS-OLD',
    scope: '临港智造',
    status: '停用',
    value: '一档,二档',
    owner: '周岚',
    note: '对应已废止政策，保留字典便于查旧档。',
  }),
]

export const affairSeed: AffairsState = {
  tasks,
  risks,
  lands,
  assessments,
  policies,
  complaints,
  submissions,
  reports,
  settings,
}
